version: 2
jobs:
  build:
    working_directory: ~/buendia

    docker:
      - image: projectbuendia/debian-stretch:1.0.0

    steps:
      - checkout # check out the code in the project directory

      - restore_cache:
          key: buendia-{{ checksum "openmrs/pom.xml" }}-{{ checksum ".circleci/config.yml" }}
          
      - run: make -C packages PACKAGE_VERSION=1.0.${CIRCLE_BUILD_NUM}

      - save_cache:
          paths:
            - ~/.m2
            - /tmp/buendia-fetched
          key: buendia-{{ checksum "openmrs/pom.xml" }}-{{ checksum ".circleci/config.yml" }}

      # Collect and store test results
      - run: >
          mkdir -p /tmp/test-results &&
          cp -a openmrs/api/target/surefire-reports /tmp/test-results/api &&
          cp -a openmrs/omod/target/surefire-reports /tmp/test-results/omod

      - store_test_results:
          path: /tmp/test-results
             
      # Collect and store artifacts
      - run: >
            mkdir -p /tmp/packages && cp $(find packages -name '*.deb') /tmp/packages

      - store_artifacts:
          path: /tmp/packages
