version: 2
jobs:
  build:
    working_directory: ~/buendia

    docker:
      - image: projectbuendia/debian-stretch:1.0.0

    steps:
      - checkout # check out the code in the project directory

      - restore_cache:
          key: buendia-{{ checksum "openmrs/pom.xml" }}
      
      - run: tools/openmrs_ensure_sdk

      - run: cd openmrs/api && mvn dependency:go-offline

      - run: cd openmrs/omod && mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
            - ~/openmrs
          key: buendia-{{ checksum "openmrs/pom.xml" }}
          
      # Main build process
      - run: make -C packages PACKAGE_VERSION=1.0.${CIRCLE_BUILD_NUM}

      # Collect and store test results
      - run: >
          mkdir -p /tmp/test-results && \
          cp -a api/target/surefire-reports /tmp/test-results/api && \
          cp -a omod/target/surefire-reports /tmp/test-results/omod

      - store_test_results:
          path: /tmp/test-results
             
      # Collect and store artifacts
      - run: >
            mkdir -p /tmp/packages && cp $(find packages -name '*.deb') /tmp/packages

      - store_artifacts:
          path: /tmp/packages
